### ISSUE TITLE
Profit/Loss Counter

### ISSUE THREAD

**Issue by Aplixux** [InfamousGangstersEnhancementSuite/IG-Enhancement-Suite#4]
**Heres an idea..**

For casino holders, not all prefer logging in and checking how much theyre down as sometimes they forget how much they logged out with, so I thought of an idea which reads your hand and when you log back it tells you whether you are in loss or in profit since your last login.

**For example:**
You can log out with $200,000,000,000 on hand and then come back with 47b profit so underneath the Money on the right menu, it should say + $47,000,000,000. This should be in a smaller font and should also have the colours Red, Green and Orange.

Red meaning Loss.
Orange meaning Even.
Green meaning Profit.

~Hasnain

**Comment by shanelja** [comment]
Thanks for your submission @Aplixux. This has been implemented in commit 84a514fff8dcd073a7d6b19f4c00a25b1435e6ca and will be released in version 2.0.3 - this should automatically update within the next 6 hours. Thank you.

Please be aware that as IGES makes no attempt to track user logins, it instead will track 10 minute intervals of your cash on hand for 5 hours worth of data.

**Comment by shanelja** [comment]
f88468a version release 2.0.3 has been created and is awaiting Chrome automated submission approval.

**Comment by shanelja** [comment]
@Aplixux This is now in production - this issue will be closed. Thanks again for raising it.
